In [ ]:
#Step 1: Install and Import NumPy
#Ensure NumPy is installed. Install it using:
!pip install numpy

In [ ]:
#import it in Python
import numpy as np

In [ ]:
#Load dataset
from google.colab import files
uploaded = files.upload()

In [ ]:
#Load the dataset babies.csv using NumPy's genfromtxt
# Load CSV file
data = np.genfromtxt('babies - babies.csv', delimiter=',', skip_header=1, dtype=float)

# Display dataset preview
print("Loaded Data (First 5 Rows):")
print(data[:5])

# Check dataset shape
print("Data Shape:", data.shape)


Loaded Data (First 5 Rows):
[[  1. 284.   0.  27.  62. 100.   0. 120.]
 [  2. 282.   0.  33.  64. 135.   0. 113.]
 [  3. 279.   0.  28.  64. 115.   1. 128.]
 [  4.  nan   0.  36.  69. 190.   0. 123.]
 [  5. 282.   0.  23.  67. 125.   1. 108.]]
Data Shape: (1236, 8)


In [ ]:
#Handle Missing Values
#Replace missing values (nan) in the dataset with the mean of the respective column
# Replace NaN values with column means
data_cleaned = np.where(np.isnan(data), np.nanmean(data, axis=0), data)

In [ ]:
#Write the Cleaned Data to a New CSV File
# Save the cleaned data to a new CSV file
# Save cleaned data to a new CSV file
np.savetxt(
    'cleaned_data.csv',
    data_cleaned,
    delimiter=',',
    fmt='%0.2f',
    header='Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8',  # Update based on actual headers
    comments=''
)

print("Cleaned data has been saved to 'cleaned_data.csv'")

Cleaned data has been saved to 'cleaned_data.csv'


In [ ]:
#Read New Dataset
data = np.genfromtxt('cleaned_data.csv', delimiter=',', skip_header=1, dtype=float)

In [ ]:
#Perform Statistical Calculations
# Mean, median, and standard deviation of the second column
second_column = data[:, 1]
mean = np.mean(second_column)
median = np.median(second_column)
std_dev = np.std(second_column)
variance= np.var(second_column)

print(f"Mean: {mean}, Median: {median}, Standard Deviation: {std_dev}")

Variance: 253.97722987060254
Mean: 279.33852750809064, Median: 280.0, Standard Deviation: 15.936663072004833


In [ ]:
# Filter rows where the first column value > 50
filtered_data = data[data[:, 0] > 50]

In [ ]:
# Save filtered data to 'filtered_data.csv'
np.savetxt('filtered_data.csv', filtered_data, delimiter=',', fmt='%0.2f', header='Column1,Column2,...')